urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from . import views

app_name = 'persons'
urlpatterns = [
    # index showing dashboard of high priority items:
    path('', views.IndexView.as_view(), name='index'),

    # autocomplete functions:
    path('autocomplete-person', 
        views.PersonAutocomplete.as_view(), 
        name='autocomplete-person',
        ),
    path('autocomplete-dept', 
        views.DeptAutocomplete.as_view(), 
        name='autocomplete-dept',
        ),
    path('autocomplete-org', 
        views.OrgAutocomplete.as_view(),
        name='autocomplete-org',
        ),
    path('autocomplete-role', 
        views.RoleAutocomplete.as_view(),
        name='autocomplete-role',
        ),

    # index views of person, department and organization:
    path('person', views.IndexPersonView.as_view(), name='person-index'),
    path('department', views.IndexDeptView.as_view(), name='dept-index'),
    path('organization', views.IndexOrgView.as_view(), name='org-index'),
    path('role', views.IndexRoleView.as_view(), name='role-index'),
    
    # create new entries for person, department and organization:
    path('person/create', views.CreatePersonView.as_view(), name='person-create'),
    path('department/create', views.CreateDeptView.as_view(), name='dept-create'),
    path('organization/create', views.CreateOrgView.as_view(), name='org-create'),
    path('role/create', views.CreateRoleView.as_view(), name='role-create'),

    # view existing entries for person, department and organization:
    path('person/<int:pk>', views.DetailPersonView.as_view(), name='person-view'),
    path('department/<int:pk>', views.DetailDeptView.as_view(), name='dept-view'),
    path('organization/<int:pk>', views.DetailOrgView.as_view(), name='org-view'),
    path('role/<int:pk>', views.DetailRoleView.as_view(), name='role-view'),

    # edit existing entries for person, department and organization:
    path('person/<int:pk>/edit', views.EditPersonView.as_view(), name='person-edit'),
    path('department/<int:pk>/edit', views.EditDeptView.as_view(), name='dept-edit'),
    path('organization/<int:pk>/edit', views.EditOrgView.as_view(), name='org-edit'),
    path('role/<int:pk>/edit', views.EditRoleView.as_view(), name='role-edit'),
    
    # search view:
    path('search/all', views.FullSearch.as_view(), name="full-search"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
from django.urls import reverse

from django.db import models

class Organization(models.Model):
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)

    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # formal identification/name of the organization/institution
    name = models.CharField(max_length=128, unique=True)
    
    # short name for display purposes
    short_name = models.CharField(max_length=16)
    
    # The organization's primary classification according to NAICS
    # definitions available at https://en.wikipedia.org/wiki/North_American_Industry_Classification_System 
    AGRICULTURE = "AG"
    MINING = "MI"
    UTILITIES = "UT"
    CONSTRUCTION = "CO"
    MANUFACTURING = "MF"
    WHOLESALE = "WS"
    RETAIL = "RT"
    TRANSPORT = "TR"
    INFORMATION = "IN"
    FINANCE = "FI"
    REALESTATE = "RE"
    SCIENTIFIC = "SC"
    MANAGEMENT = "MG"
    ADMIN = "AD"
    EDUCATIONAL = "ED"
    HEALTHCARE = "HC"
    ARTS = "AR"
    HOSPITALITY = "HS"
    GOVERNMENT = "GV"
    OTHER = "OT"

    NAICS_CHOICES = (
            (AGRICULTURE, "Agriculture, Forestry, Fishing and Hunting"),
            (MINING, "Mining, Quarrying, and Oil and Gas Extraction"),
            (UTILITIES, "Utilities"),
            (CONSTRUCTION, "Construction"),
            (MANUFACTURING, "Manufacturing"),
            (WHOLESALE, "Wholesale Trade"),
            (RETAIL, "Retail Trade"),
            (TRANSPORT, "Transportation and Warehousing"),
            (INFORMATION, "Information"),
            (FINANCE, "Finance and Insurance"),
            (REALESTATE, "Real Estate and Rental and Leasing"),
            (SCIENTIFIC, "Professional, Scientific, and Technical Services"),
            (MANAGEMENT, "Management of Companies and Enterprises"),
            (ADMIN, 
            "Administrative and Support and Waste Management and Remediation Services"),
            (EDUCATIONAL, "Educational Services"),
            (HEALTHCARE, "Health Care and Social Assistance"),
            (ARTS, "Arts, Entertainment, and Recreation"),
            (HOSPITALITY, "Accommodation and Food Services"),
            (GOVERNMENT, "Public Administration"),
            (OTHER, "Other Services"),
    )

    classification = models.CharField(
                            max_length=2,
                            choices = NAICS_CHOICES,
                            null=True,
                            blank=True,
    )
        
    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse('persons:org-view', kwargs={'pk': self.pk})
        
class Department(models.Model):
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)

    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # formal identification/name of the department
    name = models.CharField(max_length=128, unique=True)
    
    # classify the department's primary role within the institution according to NACUBO
    # definitions available at http://www.buffalo.edu/administrative-services/managing-money/state-funds/create-maintain-accts/nacubo-codes.html 
    INSTRUCTION = "ID"
    ACTIVITIES = "OA"
    RESEARCH = "OR"
    SERVICE = "PS"
    LIBRARY = "LI"
    STUDENT = "SS"
    MAINTENANCE = "MP"
    GENADMIN = "GA"
    GENINST = "GI"
    AUXILARY = "AE"
    CLINICS = "HC"
    FELLOWSHIPS = "SF"
    ADDITIONAL = "AC"
    NACUBO_CHOICES = (
                (INSTRUCTION, "Instruction and Department Research",),
                (ACTIVITIES, "Organized Activities",),
                (RESEARCH, "Organized Research",),
                (SERVICE, "Public Service",),
                (LIBRARY, "Libraries",),
                (STUDENT, "Student Services",),
                (MAINTENANCE, "Maintenance and Operation of Physical Plant",),
                (GENADMIN, "General Administration",),
                (GENINST, "General Institutional Services",),
                (AUXILARY, "Auxilary Enterprises",),
                (CLINICS, "Hospitals and Clinics",),
                (FELLOWSHIPS, "Scholarships and Fellowships",),
                (ADDITIONAL, "Additional Classifications",),
    )
    classification = models.CharField(
                            max_length=2,
                            choices = NACUBO_CHOICES,
                            null=True,
                            blank=True,
    )
        
    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse('persons:dept-view', kwargs={'pk': self.pk})
        
class Role(models.Model):
    # unique name identifying the role
    name = models.CharField(max_length=128, unique=True)
    
    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse('persons:role-view', kwargs={'pk': self.pk})
   
class Person(models.Model):
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)
    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # a unique institutional identifier for the individual
    cwid = models.CharField(max_length=16, unique=True, null=True, blank=True)
    
    # individual's preferred name, (includes first and last)
    preferred_name = models.CharField(  max_length=128,
                                        null=True,
                                        blank=True,
    )
    
    # individual's first name
    first_name = models.CharField(max_length=32)
    
    # individual's last name
    last_name = models.CharField(max_length=32)
    
    # individual's preferred pronoun
    HEHIM = "HH"
    SHEHER = "SH"
    THEYTHEM = "TT"
    ZIEZIM = "ZZ"
    OTHER = "OT"
    PRONOUN_CHOICES = (
                        (HEHIM, "He/Him/His"),
                        (SHEHER, "She/Her/Hers"),
                        (THEYTHEM, "They/Them/Theirs"),
                        (ZIEZIM, "Zie/Zim/Zir"),
                        (OTHER, "Other identification"),
    )
    pronoun = models.CharField(
                            max_length=2,
                            choices = PRONOUN_CHOICES,
                            null=True,
                            blank=True,
    )
    
    # individual's title of reference
    MR = "MR"
    MRS = "MS"
    MISS = "MI"
    MS = "MZ"
    DR = "DR"
    REV = "RV"
    SIR = "SR"
    TITLE_CHOICES = (
                (DR, "Dr"),
                (MR, "Mr"),
                (MRS, "Mrs"),
                (MISS, "Miss"),
                (MS, "Ms"),
                (REV, "Rev"),
                (SIR, "Sir") ,
                
    )
    title = models.CharField(
                            max_length=2,
                            choices=TITLE_CHOICES,
                            null=True,
                            blank=True,
    )
    
    # primary contact email
    email_primary = models.EmailField("Primary email address", 
                                        null=True, 
                                        blank=True
    )
    
    # secondary contact email
    email_secondary = models.EmailField("Secondary email address", 
                                        null=True, 
                                        blank=True
    )
    
    # phone number
    phone = models.CharField(
                            max_length=32,
                            null = True,
                            blank=True,
    )
    
    

    # organization the individual is affiliated with / employed by
    organization = models.ForeignKey(Organization, 
                                    null=True, 
                                    blank=True, 
                                    on_delete=models.CASCADE,)

    # department the individual is affiliated with / employed by
    department = models.ForeignKey(Department, 
                                    null=True, 
                                    blank=True, 
                                    on_delete=models.CASCADE,)
    
    # role the individual plays within the department / project / organization
    role = models.ForeignKey(Role, 
                             null=True, 
                             blank=True, 
                             on_delete=models.CASCADE,)
    
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        if self.preferred_name:
            name = self.preferred_name
        else:
            name = "{} {}".format(self.first_name, self.last_name)
        if self.cwid:
            id = self.cwid
        else:
            id = "---"
        
        return "{} ({})".format(name, id)

    class Meta:
        verbose_name = 'Person'
        verbose_name_plural = 'People'

    def get_absolute_url(self):
        return reverse('persons:person-view', kwargs={'pk': self.pk})

templates/persons/base-persons.html
{% extends "base.html" %}
{% load project_tags %}

{% block navblock %}
<style>
.navbar-custom {
    background-color: #CF4520;
}
/* Link */
.navbar-custom .navbar-nav > li > a {
    color: #ffffff;
}
.navbar-custom .navbar-nav > li > a:hover,
.navbar-custom .navbar-nav > li > a:focus {
    color: #ffffff;
    background-color: #E87722;
}
</style>


        <div class="navbar navbar-expand-md navbar-custom fixed-top">
                    <a class="navbar-brand" href="/">{{ APPTITLE }}</a>
                    <button class="navbar-toggler"  data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">

                        {# ## ### PERSONS DASHBOARD ### ## #}
                        <li class="nav-item active">
                          <a class="nav-link btn-outline-light"
                             href="{% url 'persons:index' %}">Persons Dashboard</a>
                        </li>

                        {# ## ### DROPDOWN ITEM INDEX PAGE LINKS ### ## #}
                        <li class="nav-item dropdown">
                
                            <a  class="nav-link dropdown-toggle btn-outline-dark"
                                href="#" id="DCDropdown"
                                role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                View Details
                            </a>
                            <div class="dropdown-menu" aria-labelledby="DCDropdown">
                                <a class="dropdown-item" href="{% url 'persons:person-index' %}">
                                    Persons</a>
                                <a class="dropdown-item" href="{% url 'persons:dept-index' %}">
                                    Departments</a>
                                <a class="dropdown-item" href="{% url 'persons:org-index' %}">
                                    Organizations</a>
                                <a class="dropdown-item" href="{% url 'persons:role-index' %}">
                                    Roles</a>
                            </div>
                        </li>
                    </ul>

                    <ul class="navbar-nav mp-auto">
                        {# ## ### PROJECT TITLE ### ## #}
                        <li>
                            <a class="nav-link mx-auto" href="#" style="fontweight:bold;color:white">
                                {% block pagetitle %}{% endblock %}</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        {# ## ### USER ADMIN OPTIONS ### ## #}
                        <li class="nav-item dropdown ml-auto">
                            <a  class="nav-link dropdown-toggle btn-outline-dark"
                                href="#" id="AdminDropdown"
                                role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                {{ user.get_username }} <b class="caret"></b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="AdminDropdown">
                              <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">
                                Admin</a>
                              <a class="dropdown-item" href="{% url 'frontpage' %}">
                                Data Core Frontpage</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="/logout">Logout </a>
                            </div>
                        </li>

                        {# ## ### USER ACTIONS ### ## #}
                        <li class="nav-item dropdown">
                            <a  class="nav-link dropdown-toggle btn-outline-dark"
                                href="#" id="ActionsDropdown"
                                role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                Submit New: <b class="caret"></b>
                            </a>
                        <div class="dropdown-menu" aria-labelledby="ActionsDropdown">
                            <a class="dropdown-item text-danger" href="{% url 'persons:person-create' %}">
                                        Person</a>
                            <a class="dropdown-item text-danger" href="{% url 'persons:dept-create' %}">
                                Department</a>
                            <a class="dropdown-item text-danger" href="{% url 'persons:org-create' %}">
                                Organization</a>
                            <a class="dropdown-item text-danger" href="{% url 'persons:role-create' %}">
                                Role</a>

                        </div>
                        </li>

                        {# ## ### SEARCH BAR ### ## #}
                        <form class="form-inline my-2 my-lg-0"
                            action="{% url 'datacatalog:full-search' %}"
                            method="post">{% csrf_token %}

                          <div class="input-group">
                          <input class="form-control" type="search"
                            placeholder="Search persons, orgs, depts..." aria-label="Search"
                            name="srch_term" id="srch_term">

                            <button class="button btn btn-secondary" type="submit">
                                Submit <i class="glyphicon glyphicon-search">
                                </i></button>
                          </div>
                        </form>

                        </ul>
            {% else %}
                <li><a  style="color:white;"
                        href="/accounts/login">Login</a></li>
            {% endif %}
        </div>
</div>


{% endblock %}

templates/persons/basic_crispy_form.html
{% extends 'persons/base-persons.html' %}

{% load static %}
{% load bootstrap4 %}

{% load crispy_forms_tags %}

{% block content %}
        
{{ form.media }}

<form action="" method="post">
	{% csrf_token %}
    {% crispy form %}
    {% comment %}
    {{ form|crispy }}
    {% endcomment %}
</form>  
    


{% endblock %}

templates/persons/basic_form.html
{% extends 'persons/base-persons.html' %}

{% load static %}
{% load bootstrap4 %}

{% load crispy_forms_tags %}

{% block content %}
        

{{ form.media }}


<form action="" method="post">
	{% csrf_token %}
    {{ form|crispy }}
    
    <input type="submit" class="btn btn-primary" value="Save" />
</form>    
    


{% endblock %}

templates/persons/detail_dept.html
{% extends 'persons/base-persons.html' %}

{# Load the tag library #}
{% load bootstrap4 %}
{% load project_tags %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}

<style>
/* styling of the tabs*/
#exTab1 .tab-content {
  color : black;
  padding : 5px 15px;
}

#exTab1 .nav-tabs > li > a {
  border-radius: 4px 4px 0 0;
}
</style>



<h1>
        {{ department.name }} 
</h1>


<h4>Classification: {{ department.get_classification_display }}</h4>

<a  class="btn btn-primary" href="{% url 'persons:dept-edit' department.pk %}">Update department details</a>

<h3>
    {{ department.person_set.count }} people in database affiliated with {{ department.name }}
</h3>

{% with department.person_set.all as person_list %}    
    {% include 'persons/table_persons.html' %}
{% endwith %}

{% endblock %}

templates/persons/detail_org.html
{% extends 'persons/base-persons.html' %}

{# Load the tag library #}
{% load bootstrap4 %}
{% load project_tags %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}

<style>
/* styling of the tabs*/
#exTab1 .tab-content {
  color : black;
  padding : 5px 15px;
}

#exTab1 .nav-tabs > li > a {
  border-radius: 4px 4px 0 0;
}
</style>



<h1>
        {{ organization.name }} 
</h1>
{% if organization.short_name %}
<h2>
    <small class="text-muted">{{ organization.short_name }}</small>
</h2>
{% endif %}

<h4>Classification: {{ organization.get_classification_display }}</h4>

<a  class="btn btn-primary" href="{% url 'persons:org-edit' organization.pk %}">Update organization details</a>

<h3>
    {{ organization.person_set.count }} people in database affiliated with {{ organization.short_name }}
</h3>

{% with organization.person_set.all as person_list %}    
    {% include 'persons/table_persons.html' %}
{% endwith %}

{% endblock %}

templates/persons/detail_person.html
{% extends 'persons/base-persons.html' %}

{# Load the tag library #}
{% load bootstrap4 %}
{% load project_tags %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}

<style>
/* styling of the tabs*/
#exTab1 .tab-content {
  color : black;
  padding : 5px 15px;
}

#exTab1 .nav-tabs > li > a {
  border-radius: 4px 4px 0 0;
}
</style>



<h1>
    {% if person.preferred_name %}
        {{ person.preferred_name }} 
    {% else %}
        {{ person.first_name }} {{ person.last_name }}
    {% endif %}
</h1>
{% if person.cwid %}
<h2>
    <small class="text-muted">{{ person.cwid }}</small>
</h2>
{% endif %}

<h4>Personal details</h4>
<table class="table table-striped table-hover" id="PersonalDetails">
<thead class="thead-default">
    <tr>
        <th>Preferred name</th>
        <th>Title</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Preferred pronoun</th>
        <th>CWID</th>
    </tr>
</thead>

    <tr>
        <td>{{ person.preferred_name }}</td>
        <td>{{ person.get_title_display }}</td>
        <td>{{ person.first_name }}</td>
        <td>{{ person.last_name }}</td>
        <td>{{ person.get_pronoun_display }}</td>
        <td>{{ person.cwid }}
    </tr>
</table>

<h4>Affiliation details</h4>

<table class="table table-striped table-hover">
    {% if person.organization %}
    <tr>
        <td>Organization</td>
        <td><a href="{% url 'persons:org-view' person.organization.pk %}">
                {{ person.organization }}</a></td>
    </tr>
    {% endif %}
    {% if person.department %}
    <tr>
        <td>Department</td>
        <td><a href="{% url 'persons:dept-view' person.department.pk %}">
            {{ person.department }}</a></td>
    </tr>
    {% endif %}
    {% if person.role %}
    <tr>
        <td>Role</td>
        <td><a href="{% url 'persons:role-view' person.role.pk %}">
            {{ person.role }}</a></td>
    </tr>
    {% endif %}
    </table>
    
<h4>Contact details</h4>    
    <table class="table table-striped table-hover">
    <tr>
        <td>Primary email</td>
        <td>{{ person.email_primary }}</td>
    </tr>
    <tr>
        <td>Secondary email</td>
        <td>{{ person.email_secondary }}</td>
    </tr>
    <tr>
        <td>Phone</td>
        <td>{{ person.phone }}</td>
    </tr>
    </table>
{% if person.comments %}
    <h4>Contact details</h4>
    <p>{{ person.comments|linebreaks}}</p>    
{% endif %}
    
    

{% if request.user|has_group:"datacatalog_editor" %}
<a  class="btn btn-primary" href="{% url 'persons:person-edit' person.pk %}">Update person details</a>
{% endif %}

{% endblock %}

templates/persons/index_depts.html
{% extends 'persons/base-persons.html' %}

{% block content %}
<h1>
Index of all {{ dept_list|length }} departments
</h1>

<a  class="btn btn-primary" href="{% url 'persons:dept-create' %}">Add new department</a>

{% include 'persons/table_depts.html' %}

{% endblock content %}

templates/persons/index_orgs.html
{% extends 'persons/base-persons.html' %}

{% block content %}
<h1>
Index of all {{ org_list|length }} organizations
</h1>

<a  class="btn btn-primary" href="{% url 'persons:org-create' %}">Add new organization</a>

{% include 'persons/table_orgs.html' %}

{% endblock content %}

templates/persons/index_person.html
{% extends 'persons/base-persons.html' %}

{% block content %}
<h1>
Index of all {{ person_list|length }} people
</h1>

<a  class="btn btn-primary" href="{% url 'persons:person-create' %}">Add new person</a>

{% include 'persons/table_persons.html' %}

{% endblock content %}

templates/persons/index_roles.html
{% extends 'persons/base-persons.html' %}

{% block content %}
<h1>
Index of all {{ role_list|length }} roles
</h1>

<a  class="btn btn-primary" href="{% url 'persons:role-create' %}">Add new role</a>

{% include 'persons/table_roles.html' %}

{% endblock content %}

templates/persons/table_depts.html
<table class="table table-striped table-hover" id="PersonTable">
<thead class="thead-default">
    <tr>
        <th>Name</th>
        <th>Category</th>
    </tr>
</thead>

{% for d in dept_list %}
    <tr>
    <td><a href="{% url 'persons:dept-view' d.pk %}">{{ d.name }}</a></td>
    <td>{{ d.get_classification_display }}</td>
    </tr>
{% endfor %}
</table>

templates/persons/table_orgs.html
<table class="table table-striped table-hover" id="PersonTable">
<thead class="thead-default">
    <tr>
        <th>Name</th>
        <th>Short Name</th>
        <th>Classification</th>
    </tr>
</thead>

{% for o in org_list %}
    <tr>
    <td><a href="{% url 'persons:org-view' o.pk %}">{{ o.name }}</a></td>
    <td>{{ o.short_name }}</td>
    <td>{{ o.get_classification_display }}</td>
    </tr>
{% endfor %}
</table>

templates/persons/table_persons.html
<table class="table table-striped table-hover" id="PersonTable">
<thead class="thead-default">
    <tr>
        <th>Preferred name</th>
        <th>Title</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Preferred pronoun</th>
        <th>CWID</th>
    </tr>
</thead>

{% for p in person_list %}
    <tr>
    <td><a href="{% url 'persons:person-view' p.pk %}">{{ p.preferred_name }}</a></td>
    <td>{{ p.get_title_display }}</td>
    <td>{{ p.first_name }}</td>
    <td>{{ p.last_name }}</td>
    <td>{{ p.get_pronoun_display }}</td>
    <td>{{ p.cwid }}</td>
    </tr>
{% endfor %}
</table>

templates/persons/table_roles.html
<table class="table table-striped table-hover" id="PersonTable">
<thead class="thead-default">
    <tr>
        <th>Role Name</th>
    </tr>
</thead>

{% for r in role_list %}
    <tr>
    <td><a href="{% url 'persons:role-view' r.pk %}">{{ r.name }}</a></td>
    </tr>
{% endfor %}
</table>